#!/usr/bin/env perl
use lib 'src';
use 5.010;
use strict;
use warnings;

use Bennu::Compiler;
use Data::Dumper;

my $compiler = Bennu::Compiler->new;

my $ast = $compiler->compilefile($ARGV[0]);
my $packages = $compiler->PACKAGE;
my $lex = $compiler->SCOPE;

say Dumper $ast, $packages, $lex;

# Local Variables:
#   mode: cperl
# End:
